server:
  port: 8080

common: &common
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.jdbc.Driver
  # 初始化时建立物理连接的个数
  initialSize: 5
  # 最小连接池数量
  minIdle: 5
  # 最大连接池数量
  maxActive: 201
  # 获取连接时最大等待时间，单位毫秒
  maxWait: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
  # 连接保持空闲而不被驱逐的最小时间
  minEvictableIdleTimeMillis: 300000
  # 用来检测连接是否有效的sql，要求是一个查询语句
  validationQuery: SELECT 1 FROM DUAL
  # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
  testWhileIdle: true
  # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
  testOnBorrow: false
  # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
  testOnReturn: false
  # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
  poolPreparedStatements: false
  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  aop-patterns: "cc.ljb.mysql.mapper.*"
  filters: stat,wall
  filter:
    stat:
      enabled: ture
      db-type: mysql
      log-show-sql: true
      slow-sql-millis: 100
  # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
  maxPoolPreparedStatementPerConnectionSize: 20
  # 合并多个DruidDataSource的监控数据
  useGlobalDataSourceStat: true
  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

spring:
  shardingsphere:
    datasource:
      names: master,slave0,slave1
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3001/student?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useAffectedRows=true&useSSL=false
        username: root
        password: root123
        <<: *common
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3002/student?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useAffectedRows=true&useSSL=false
        username: root
        password: root123
        <<: *common
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3003/student?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useAffectedRows=true&useSSL=false
        username: root
        password: root123
        <<: *common
    enabled: true
    props:
      sql-show: true
    rules:
      readwrite-splitting:
        data-sources:
          master-slave:
            props:
              auto-aware-data-source-name: master
              read-data-source-names: slave0,slave1
              write-data-source-name: master
            type: Static
            loadBalancerName: round-robin
          load-balancers:
            round-robin:
              type: ROUND_ROBIN
#              type: WEIGHT
#              props:
#                slave0: 1
#                slave1: 2

mybatis:
  configuration.cache-enabled: true
  mapper-locations: classpath:mappers/*.xml
