server:
  port: 8080

spring:
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3001/pubsub?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useAffectedRows=true&useSSL=false
        username: root
        password: root123
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3002/pubsub?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useAffectedRows=true&useSSL=false
        username: root
        password: root123
    enabled: true
    props:
      sql:
        show: true
      sql-show: true
    rules:
      readwrite-splitting:
        data-sources:
          load-balancers:
            roundRobin:
              type: ROUND_ROBIN
          master-slave:
            props:
              auto-aware-data-source-name: master
              load-balancer-name: roundRobin
              read-data-source-names: slave
              write-data-source-name: master
            type: Static

mybatis:
  configuration.cache-enabled: true
  mapper-locations: classpath:mappers/*.xml
