server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pubsub?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useAffectedRows=true&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: root321
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    cc.ljb.mysqlbatchinsert.mapper : warn

mybatis:
#  configuration.cache-enabled: true
  mapper-locations: classpath:mappers/*.xml
